name: 'Setup composer dependencies'
description: 'Sets up composer dependencies for the workflow'
inputs:
  php-version:
    description: 'Version of PHP to use for the workflow'
    required: true
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      id: cache-composer
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-${{ inputs.php-version }}-composer-${{ hashFiles('composer.lock') }}

    - if: ${{ steps.cache-composer.outputs.cache-hit != 'true' }}
      name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader
      shell: bash