name: CI

on:
  workflow_call:
  workflow_dispatch:

jobs:
  fix-code-style:
    runs-on: ubuntu-22.04

    timeout-minutes: 10

    steps:
      - uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2.37.0
        with:
          php-version: "8.4"
          coverage: none

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Dependencies
        uses: ./.github/actions/composer-dependency-setup

      - name: Cache PHP CS Fixer
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: .php-cs-fixer.cache
          key: ${{ runner.OS }}-${{ github.repository }}-phpcsfixer-${{ github.run_id }}
          restore-keys: |
            ${{ runner.OS }}-${{ github.repository }}-phpcsfixer-

      - name: Run Formatters
        run: composer format

      - name: Check for changes
        uses: tj-actions/verify-changed-files@a1c6acee9df209257a246f2cc6ae8cb6581c1edf # v20.0.4
        with:
          fail-if-changed: "true"

  test:
    strategy:
      matrix:
        php-version: ["8.3", "8.4", "8.5"]

    runs-on: ubuntu-22.04

    timeout-minutes: 15

    steps:
      - uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2.37.0
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Dependencies
        uses: ./.github/actions/composer-dependency-setup
        with:
          php-version: "${{ matrix.php-version }}"

      - name: Execute tests
        run: composer test

  static-analysis:
    strategy:
      matrix:
        php-version: ["8.3", "8.4", "8.5"]

    runs-on: ubuntu-22.04

    timeout-minutes: 15

    steps:
      - uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2.37.0
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Dependencies
        uses: ./.github/actions/composer-dependency-setup
        with:
          php-version: "${{ matrix.php-version }}"

      - name: "Result Cache for PHPStan"
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: /tmp/phpstan
          key: "${{ runner.OS }}-${{ github.repository }}-static-analysis-${{ matrix.php-version }}-${{ github.run_id }}"
          restore-keys: |
            ${{ runner.OS }}-${{ github.repository }}-static-analysis-${{ matrix.php-version }}-

      - name: Run PHPStan
        run: composer analyze